
# ACCUEIL
route_accueil:
    path: /accueil
    controller: App\Controller\GoatController::index
#RESPONSABLE
ResponsableLister:
    path: /responsable/lister/
    controller: App\Controller\ResponsableController::listerResponsable
consulterResponsable:
    path: /responsable/consulter/{id}
    controller: App\Controller\ResponsableController::consulterResponsable
# ELEVE  
eleveLister:
    path: /eleve/lister/
    controller: App\Controller\EleveController::listerEleve
eleveConsulter:
    path: /eleve/consulter/{id}
    controller: App\Controller\EleveController::consulterEleve
eleveAjouter:
    path: /eleve/ajouter/
    controller: App\Controller\EleveController::ajouter
etudiantModifier:
    path: /eleve/modifier/{id}
    controller: App\Controller\EleveController::modifierEleve
etudiantSupprimer:
    path: eleve/supprimer/{id}
    controller: App\Controller\EleveController::supprimerEleve
# COUR
coursLister:
    path: /cours/lister/
    controller: App\Controller\CoursController::listerCours
coursConsulter:
    path: /cours/consulter/{id}
    controller: App\Controller\CoursController::consulterCours
coursAjouter:
    path: /cours/ajouter/
    controller: App\Controller\CoursController::ajouter
cousrModifier:
    path: /cours/modifier/{id}
    controller: App\Controller\CoursController::modifierCours
#INSTRUMENT
instrumentConsulter:
    path: /instrument/consulter/{id}
    controller: App\Controller\InstrumentController::consulterInstrument
instrumentAjouter:
    path: /instrument/ajouter
    controller: App\Controller\InstrumentController::ajouter
instrumentLister:
    path: /instrument/lister
    controller: App\Controller\InstrumentController::lister
instrumentModifier:
    path: /instrument/modifier/{id}
    controller: App\Controller\InstrumentController::modifierinstrument
#PROFFESSEUR
professeurConsulter:
    path: /professeur/consulter/{id}
    controller: App\Controller\ProfesseurController::consulterProfesseur
professeurLister:
    path: /professeur/lister
    controller: App\Controller\ProfesseurController::listerProfesseur
