controllers:
    resource: ../src/Controller/
    type: attribute

professeurConsulter:
    path: /professeur/consulter/{id}
    controller: App\Controller\ProfesseurController::consulterProfesseur
professeurLister:
    path: /professeur/lister
    controller: App\Controller\ProfesseurController::listerProfesseur