
# ACCUEIL
route_accueil:
    path: /utilisateur/accueil
    controller: App\Controller\GoatController::index
#RESPONSABLE
ResponsableLister:
    path: /admin/responsable/lister/
    controller: App\Controller\ResponsableController::listerResponsable
consulterResponsable:
    path: /admin/responsable/consulter/{id}
    controller: App\Controller\ResponsableController::consulterResponsable
# ELEVE  
eleveLister:
    path: /admin/eleve/lister/
    controller: App\Controller\EleveController::listerEleve
eleveConsulter:
    path: /admin/eleve/consulter/{id}
    controller: App\Controller\EleveController::consulterEleve
eleveAjouter:
    path: /admin/eleve/ajouter/
    controller: App\Controller\EleveController::ajouter
etudiantModifier:
    path: /admin/eleve/modifier/{id}
    controller: App\Controller\EleveController::modifierEleve
etudiantSupprimer:
    path: /admin/eleve/supprimer/{id}
    controller: App\Controller\EleveController::supprimerEleve
# COUR
coursLister:
    path: /utilisateur/cours/lister/
    controller: App\Controller\CoursController::listerCours
coursConsulter:
    path: /utilisateur/cours/consulter/{id}
    controller: App\Controller\CoursController::consulterCours
coursAjouter:
    path: /admin/cours/ajouter/
    controller: App\Controller\CoursController::ajouter
cousrModifier:
    path: /admin/cours/modifier/{id}
    controller: App\Controller\CoursController::modifierCours
coursSupprimer:
    path: /admin/cours/supprimer/{id}
    controller: App\Controller\CoursController::supprimerCours
#INSTRUMENT
instrumentConsulter:
    path: /utilisateur/instrument/consulter/{id}
    controller: App\Controller\InstrumentController::consulterInstrument
instrumentConsulterType:
    path: /utilisateur/instrument/consulterType/{id}
    controller: App\Controller\InstrumentController::consulterTypeInstrument
instrumentAjouter:
    path: /admin/instrument/ajouter
    controller: App\Controller\InstrumentController::ajouter
instrumentLister:
    path: /utilisateur/instrument/lister
    controller: App\Controller\InstrumentController::lister
instrumentListerType:
    path: /utilisateur/instrument/listerType
    controller: App\Controller\InstrumentController::listerType
instrumentModifier:
    path: /admin/instrument/modifier/{id}
    controller: App\Controller\InstrumentController::modifierInstrument
instrumentSupprimer:
    path: /admin/instrument/supprimer/{id}
    controller: App\Controller\InstrumentController::supprimerInstrument
#PROFFESSEUR
professeurConsulter:
    path: /utilisateur/professeur/consulter/{id}
    controller: App\Controller\ProfesseurController::consulterProfesseur
professeurLister:
    path: /utilisateur/professeur/lister
    controller: App\Controller\ProfesseurController::listerProfesseur
professeurAjouter:
    path: /admin/professeur/ajouter
    controller: App\Controller\ProfesseurController::ajouterProfesseur
professeurModifier:
    path: /admin/professeur/modifier/{id}
    controller: App\Controller\ProfesseurController::modifierProfesseur
professeurSupprimer:
    path: /admin/professeur/supprimer/{id}
    controller: App\Controller\ProfesseurController::supprimerProfesseur
#ACCESSOIRE
accessoireAjouter:
    path: /admin/accessoire/ajouter
    controller: App\Controller\AccessoireController::ajouter
accessoireConsulter:
    path: /admin/accessoire/consulter/{id}
    controller: App\Controller\AccessoireController::consulterAccessoire
#MARQUE
marqueAjouter:
    path: /admin/marque/ajouter
    controller: App\Controller\MarqueController::ajouter
marqueConsulter:
    path: /admin/accessoire/consulter/{id}
    controller: App\Controller\MarqueController::consulterMarque
#COULEUR
couleurAjouter:
    path: /admin/couleur/ajouter
    controller: App\Controller\CouleurController::ajouter
couleurConsulter:
    path: /admin/couleur/consulter/{id}
    controller: App\Controller\CouleurController::consulterCouleur
#TYPEINSTRUMENT
typeInstrumentAjouter:
    path: /type_instrument/ajouter
    controller: App\Controller\TypeInstrumentController::ajouter
typeInstrumentConsulter:
    path: /utilisateur/type_instrument/consulter/{id}
    controller: App\Controller\TypeInstrumentController::consulterTypeInstrument
typeInstrumentLister:
    path: /utilisateur/type_instrument/lister
    controller: App\Controller\TypeInstrumentController::lister
typeInstrumentConsulterType:
    path: /utilisateur/type_instrument/consulterType/{id}
    controller: App\Controller\TypeInstrumentController::consulterTypeInstrument
#USER
UserConsulter:
    path: /utilisateur/user/information/
    controller: App\Controller\UserController::index
#LOGIN
app_login:
    path: /utilisateur/login
    controller: App\Controller\LoginController::index
app_register:
    path: /utilisateur/register
    controller: App\Controller\RegistrationController::register
app_logout:
    path: /utilisateur/logout
    methods: GET


