
# ACCUEIL
route_accueil:
    path: /accueil
    controller: App\Controller\GoatController::index
#RESPONSABLE
ResponsableLister:
    path: /responsable/lister/
    controller: App\Controller\ResponsableController::listerResponsable
consulterResponsable:
    path: /responsable/consulter/{id}
    controller: App\Controller\ResponsableController::consulterResponsable
# ELEVE  
eleveLister:
    path: /eleve/lister/
    controller: App\Controller\EleveController::listerEleve
eleveConsulter:
    path: /eleve/consulter/{id}
    controller: App\Controller\EleveController::consulterEleve
eleveAjouter:
    path: /eleve/ajouter/
    controller: App\Controller\EleveController::ajouter
etudiantModifier:
    path: /eleve/modifier/{id}
    controller: App\Controller\EleveController::modifierEleve
etudiantSupprimer:
    path: eleve/supprimer/{id}
    controller: App\Controller\EleveController::supprimerEleve
# COUR
coursLister:
    path: /cours/lister/
    controller: App\Controller\CoursController::listerCours
coursConsulter:
    path: /cours/consulter/{id}
    controller: App\Controller\CoursController::consulterCours
coursAjouter:
    path: /cours/ajouter/
    controller: App\Controller\CoursController::ajouter
cousrModifier:
    path: /cours/modifier/{id}
    controller: App\Controller\CoursController::modifierCours
coursSupprimer:
    path: /cours/supprimer/{id}
    controller: App\Controller\CoursController::supprimerCours
#INSTRUMENT
instrumentConsulter:
    path: /instrument/consulter/{id}
    controller: App\Controller\InstrumentController::consulterInstrument
instrumentAjouter:
    path: /instrument/ajouter
    controller: App\Controller\InstrumentController::ajouter
instrumentLister:
    path: /instrument/lister
    controller: App\Controller\InstrumentController::lister
instrumentModifier:
    path: /instrument/modifier/{id}
    controller: App\Controller\InstrumentController::modifierInstrument
instrumentSupprimer:
    path: instrument/supprimer/{id}
    controller: App\Controller\InstrumentController::supprimerInstrument
#PROFFESSEUR
professeurConsulter:
    path: /professeur/consulter/{id}
    controller: App\Controller\ProfesseurController::consulterProfesseur
professeurLister:
    path: /professeur/lister
    controller: App\Controller\ProfesseurController::listerProfesseur
professeurAjouter:
    path: /professeur/ajouter
    controller: App\Controller\ProfesseurController::ajouterProfesseur
professeurModifier:
    path: /professeur/modifier/{id}
    controller: App\Controller\ProfesseurController::modifierProfesseur
professeurSupprimer:
    path: professeur/supprimer/{id}
    controller: App\Controller\ProfesseurController::supprimerProfesseur
#ACCESSOIRE
accessoireAjouter:
    path: /accessoire/ajouter
    controller: App\Controller\AccessoireController::ajouter
accessoireConsulter:
    path: /accessoire/consulter/{id}
    controller: App\Controller\AccessoireController::consulterAccessoire
#MARQUE
marqueAjouter:
    path: /marque/ajouter
    controller: App\Controller\MarqueController::ajouter
marqueConsulter:
    path: /accessoire/consulter/{id}
    controller: App\Controller\MarqueController::consulterMarque
#COULEUR
couleurAjouter:
    path: /couleur/ajouter
    controller: App\Controller\CouleurController::ajouter
couleurConsulter:
    path: /couleur/consulter/{id}
    controller: App\Controller\CouleurController::consulterCouleur
#TYPEINSTRUMENT
typeInstrumentAjouter:
    path: /typeInstrument/ajouter
    controller: App\Controller\TypeInstrumentController::ajouter
typeInstrumentConsulter:
    path: /typeInstrument/consulter/{id}
    controller: App\Controller\TypeInstrumentController::consulterTypeInstrument
app_login:
    path: /login
    controller: App\Controller\LoginController::index
app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
app_logout:
    path: /logout
    methods: GET
