controllers:
    resource: ../src/Controller/
    type: attribute
route_accueil:
    path: /accueil
    controller: App\Controller\AccueilController::index
#RESPONSABLE
ResponsableLister:
    path: /responsable/lister/
    controller: App\Controller\ResponsableController::listerResponsable

consulterResponsable:
    path: /responsable/consulter/{id}
    controller: App\Controller\ResponsableController::consulterResponsable

